name: black_ops_6_zombie_tools
description: "A tools for Black Ops 6 Zombie"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: any
  flutter_svg: any
  logging: any
  url_launcher: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: any
  launcher_name: any

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/platform/
    - assets/images/flags/
    - assets/images/universal/
    - assets/images/maps/terminus/dri11/
    - assets/images/maps/citadelle_des_morts/void_sword/
    - assets/images/maps/citadelle_des_morts/rune_puzzle/

launcher_name:
  default: "Black Ops 6 Tools"
